version: '3'

services:

  mysql-development:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: spaceshop
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - "3308:3306"
    volumes:
      - ./mysql_data/:/var/lib/mysql
  admin:
    image: adminer
    ports:
      - "8080:8080"
